spring:
  application:
    name: ${SPRING_APP_NAME:api_reports}
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 500MB
  jpa:
    open-in-view: false

server:
  port: ${SERVER_PORT:8080}

file:
  upload:
    dir: uploads/reports
    max-size-bytes: 209715200
